### PR TITLE
Add Whatsapp option for result page.

### PR DESCRIPTION
**Pull request by baharbazargan62**
## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Review by Miladepour — APPROVED** [review]
Thanks, Cuneyt.
I reviewed and tested it. Everything works perfectly.

**Comment by Miladepour** [comment]
Please AVOID merging this until PR #51 has been approved and merged. There have been some changes to the design that need to be incorporated into your branch before merging.

**Comment by natyfromwonderland** [comment]
Hi! A couple of questions. Will the phone number be added automatically? Will the Spinner be added as well? Thank you!

**Comment by Miladepour** [comment]
> Hi! A couple of questions. Will the phone number be added automatically? Will the Spinner be added as well? Thank you!

Now it's ready and everything is updated with the latest changes.

**Review by natyfromwonderland — APPROVED** [review]
Thanks all! let's now concentrate on testing!

**Pull request merged**
