### PR TITLE
localization

### PR DESCRIPTION
**Pull request by haroon-ali-dev**
#64
added localization to user side navbar, footer, home page, about page, user form page user preferences page and result page.

to test just add `lng: "hi"` to `i18n.js` on line 12. **But make sure you remove it after please.**

### CODE REVIEW

**Review by Miladepour — APPROVED** [review]
Thanks, Haroon, Everything looks fine.
I finished my review

**Comment by natyfromwonderland** [comment]
I think this one is dependent on Milad's cosmetic changes?

**Comment by natyfromwonderland** [comment]
Hi again, are you going to add 'about' section or shall we add this to the next sprint/ team given the time?

**Comment by haroon-ali-dev** [comment]
@natyfromwonderland 
after the cosmetic PR is merged, I can add localization to all those remaining sections.

**Review by natyfromwonderland — APPROVED** [review]
Thanks @haroon-ali-dev! Well done on putting the framework for the multiple language support!

**Review by Miladepour — CHANGES_REQUESTED** [review]

**Review by Miladepour — APPROVED** [review]
I finished my review

**Pull request merged**
