### PR TITLE
remove all dummy data

### PR DESCRIPTION
**Pull request by haroon-ali-dev**
#45 removed all dummy data.

### CODE REVIEW

**Review by Miladepour — APPROVED** [review]
I finished my review.

**Comment by EneVladMihai** [comment]
Having sample data in the repo is still useful. It will help someone new to the codebase understand how data is structured and what fields each object type has. What is the motivation for deleting it? (Instead of deleting I'd suggested updating it to make sure field names match the ones in the db and that it does not contain real data)

**Comment by natyfromwonderland** [comment]
Hi, thought that info on table schemas should be in the Readme along with other setup info? He deleted the original json files we used for the frontend before it got connected to backend. We still have sql setups?

**Comment by haroon-ali-dev** [comment]
@EneVladMihai @natyfromwonderland 
what should I do then?

**Comment by EneVladMihai** [comment]
That makes sense @natyfromwonderland , but having a few data samples is still worth it. Even if you have the schema - it's like a definition + example, they complement each other.

@haroon-ali-dev I'd say make sure that the dummy data matches the current data format (e.g. json field for contacts) and keep 2-3 examples for each. In the data folder you could add a short Readme describing the schema. (Some formatting ideas here are to have markdown tables where the col names are the fields and the first row are the types or to have json-like objects where the key is the field and the value is the type)

id           | name
------------------------------------
auto int | varchar (255)

Or 

```
user: {
  id: auto int,
  name: varchar(255)
}
```

**Comment by haroon-ali-dev** [comment]
@EneVladMihai 
I've done it. Please check.

**Review by EneVladMihai — APPROVED** [review]

**Pull request merged**
